name: '[🐛] Report a bug'
description: Is something unexpected happening? Report it here.
title: '[🐛Bug]: '
labels:
  - bug
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug in a few words
      description: What happens when the bug occurs?
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: What are the steps to reproduce the bug? If you can, send us some screenshots and/or screen recordings.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What did actually happen?
    validations:
      required: true
  - type: textarea
    id: errors
    attributes:
      label: Error/exception messages
      description: If an error or exception message is shown in your terminal, please paste it here.
    validations:
      required: false
  - type: dropdown
    id: py_version
    attributes:
      label: Python version
      description: What's the Python version you're using to reproduce the bug?
      options:
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Python 3.13 (beta)
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: >-
        What's the operating system and its version you used to reproduce the bug?
      placeholder: E.g. Windows 11 23H2
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Duplicate check
      options:
        - label: >-
            I checked the issue tracker and I can confirm that my bug was not already reported by someone else
          required: true
