name: '[❓] Ask a question'
description: Do you want something to be clarified? Use this template!
title: '[❓Question]: '
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's your question?
    validations:
      required: true
