name: '[❓] Ask a question'
description: Do you want something to be clarified? Use this template!
title: '[❓Question]: '
labels:
  - question
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's your question?
    validations:
      required: true
  - type: checkboxes
    id: check
    attributes:
      label: Duplicate check
      options:
        - label: >-
            I checked the issue tracker and I can confirm that my question was
            not already answered in another issue created by someone else.
          required: true
